### ISSUE TITLE
AppImage not launching

### ISSUE THREAD

**Issue by despens** [webrecorder/replayweb.page#20]
Downloaded the latest AppImage release 1.1.0 from GitHub, it doesn't start on Ubuntu 20.04.

Unfortunately there is not much meaningful debugging output:

```console
despens@slice:~/bin$ chmod a+x ReplayWeb.page-1.1.0.AppImage 
despens@slice:~/bin$ ./ReplayWeb.page-1.1.0.AppImage 
bash: ./ReplayWeb.page-1.1.0.AppImage: No such file or directory
```

Double-clicking from the file manager doesn't launch a new task.

There are no issues with other AppImages on my system.

**Comment by ikreymer** [comment]
It appears that AppImage binaries are 32-bit, instead of 64-bit. Looking into why that may be...

**Comment by ikreymer** [comment]
This is due to the fact that the Windows & Linux builds are combined into one pass, as suggested at:
https://www.electron.build/multi-platform-build

The windows build is a combined 32-bit and 64-bit, to support 32-bit windows, but that results in the AppImage also being 32-bit.

Probably should separate out the AppImage and Windows builds and do only 64-bit AppImage.

**Comment by ikreymer** [comment]
Manually updated AppImage to 64-bit binary for the 1.1.0, will be built as such going forward.
