### ISSUE TITLE
[Replay Bug]: pages don't display properly

### ISSUE THREAD

**Issue by robert-1043** [webrecorder/replayweb.page#360]
### ReplayWeb.page Version

all versions (most recent web + standalone & standalone 1.8.17)

### What did you expect to happen? What happened instead?

I am archiving 2 websites with similar front- and backend.  The overview pages don't replay properly on the full archives (12k & 28k pages).  When the archive is limited to 100 pages, the replay is rather correct.  (That is: extra content is loaded when scrolling down, at the end the replay continues to add the same content.)

### Additional details

Will transfer both wacz to info @ webrecorder with additional references.

**Comment by nvanderperren** [comment]
I also have a problem with instagram replay since this week. Just when I have to do a tutorial about this on iPRES 😢  I can't slide through images. Two weeks ago it worked perfectly. It's an instagram page that was archived with archiveweb.page. When an Instagram post has multiple images, I can't slide through the images anymore in replayweb.page. In the replay page of archiveweb.page it works perfectly, but the page is very zoomed out there.

**Comment by ikreymer** [comment]
@nvanderperren sorry to hear that -- if you share the WACZ files, we can try to take a look. there weren't any particular changes to replay to cause that that I'm aware of.

@robert-1043 we've received the files, thanks, will take a look when we can - (these issues are likely unrelated)

**Comment by ikreymer** [comment]
@robert-1043 does this mean this can be closed then? sorry, i think we didn't get to investigate the original issue, can you confirm if it is fixed now?

**Comment by robert-1043** [comment]
Yes, as the issue of some content being repeated may have to do with the capture (see crawler #723).
