### ISSUE TITLE
URLs are being sufixed with "null"

### ISSUE THREAD

**Issue by gjvnq** [webrecorder/replayweb.page#60]
Whenever I try to access a page, the program fails and claims I tried to access a different page than the one I asked.

Example: I asked for ```http://127.0.0.1:8000/gdb/pt``` but I get an error message saying:

> This page http://127.0.0.1:8000/gdb/ptnull is not part of this archive.

![Screenshot from 2021-08-05 02-03-30](https://user-images.githubusercontent.com/3050524/128293733-1129272c-df0f-4687-a08a-00ced92433cd.png)

File I tried to load: [biblia-disforia-genero-pt.har.txt](https://github.com/webrecorder/replayweb.page/files/6936028/biblia-disforia-genero-pt.har.txt) Plase not that I had to change the file extension in order to upload it to GitHub. Just remove the final ```.txt``` and you should be fine.

**Comment by ikreymer** [comment]
Thanks for reporting! I think there's actually two separate issues:
1) Something seems wrong with HAR loading
2) There's a bug that adds `null` (was trying to add hashtag) at the end of pages that are 404, which makes it more confusing.

**Comment by ikreymer** [comment]
Will post a fix shortly, which will fix the very last page in the HAR file (was broken due to redirect being filtered out).

Unfortunately, most of the content for the other pages has not been included.

You can see this by looking at the HAR file and seeing that most of the data has:

```
         "content": {
            "size": 0,
            "mimeType": "text/html",
            "compression": 0
          },
```

When creating HAR files in the browser, it's typical for the browser to only include the data for last page, and drop everything else.

To avoid this, you can use our ArchiveWeb.page extension which can capture data across multiple pages.

**Comment by ikreymer** [comment]
Now fixed, the last page captured should now work, the other pages will display an error due to missing content.
(Will be in 1.4.7 release but up on replayweb.page now)

**Comment by gjvnq** [comment]
@ikreymer Thanks!
