### ISSUE TITLE
Can't load archive over https in Firefox

### ISSUE THREAD

**Issue by codl** [webrecorder/replayweb.page#74]
Hi, I'm having trouble loading archives over https in Firefox

Here is the archive i've been testing with: <https://f.codl.fr/2201/test.warc.gz>
and how I'm loading it into replayweb.page: <https://replayweb.page/?source=https%3A%2F%2Ff.codl.fr%2F2201%2Ftest.warc.gz#url=https%3A%2F%2Ff.codl.fr%2Fdancing_baby.gif>

When I load it into Chrome, it loads up fine. When I load it in Firefox, it fails with "An unexpected error occured: TypeError: NetworkError when attempting to fetch resource."

Firefox's console complains further about CORS:
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://f.codl.fr/2201/test.warc.gz. (Reason: CORS request did not succeed). Status code: (null).
>
> Failed to load ‘https://f.codl.fr/2201/test.warc.gz’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.

However I believe I am serving sufficient CORS headers [per the documentation](https://replayweb.page/docs/embedding#cors-restrictions):
```
$ curl -Is "https://f.codl.fr/2201/test.warc.gz" | grep access-control    
access-control-allow-origin: *
access-control-allow-methods: GET, POST, OPTIONS, HEAD
access-control-expose-headers: Content-Encoding, Content-Range, Content-Length
access-control-allow-headers: *
```

**Comment by ikreymer** [comment]
Looks like this wasn't working in Chrome 96 but it was just fixed in Chrome 97, due to: https://bugs.chromium.org/p/chromium/issues/detail?id=1255711

Previously, using the `Range` header as replayweb.page does required a "pre-flight" OPTIONS request, so the server must also respond to OPTIONS and indicate that it supports the Range header. But, looks like this was recently fixed in Chrome, which is actually great as it should speed up the loading.
Looks like Firefox has not yet implemented this though.

To make this work in Firefox, you'll need to have `curl -XOPTONS "https://f.codl.fr/2201/test.warc.gz` return a 200,
and also include `access-control-allow-headers: range`. Unfortunately, FF does not show the pre-flight request in devtools so its harder to see what is erroring, but you should be able to see in your server logs that there is an OPTIONS request.

Hope this helps, and interesting to note about this change in Chrome..

**Comment by codl** [comment]
Thank you. I had assumed that NGINX would handle OPTIONS requests on its own, now that I've done it manually it all seems to work.

This seems like something that would be worth documenting, especially now that some browsers need it and others don't

**Comment by ikreymer** [comment]
We've added additional docs for configuring CORS here, which includes nginx settings and differences between browsers: https://replayweb.page/docs/cors-settings
